[package]
name = "kvs"
version = "0.1.0"
authors = ["ymgyt <yamaguchi7073xtt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3.1", features = ["rt", "rt-multi-thread", "io-util", "net", "stream", "signal", "fs","sync"]}
bytes = "0.6"
tracing = "0.1.21"
chrono = "0.4.19"
backtrace = "0.3.53"

[dev-dependencies]
tokio-test = { version = "0.3.0"}
