[package]
name = "kvs"
version = "0.1.0"
authors = ["ymgyt <yamaguchi7073xtt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["cli"]
cli = ["tracing-subscriber"]

[dependencies]
tokio = { version = "0.3.2", features = ["rt", "rt-multi-thread", "io-util", "net", "stream", "signal", "fs","sync", "macros"] }
bytes = "0.6"
tracing = "0.1.21"
chrono = "0.4.19"
backtrace = "0.3.53"
crc32fast = "1.2.1"
num_cpus = "1.13.0"
tracing-subscriber = { version = "0.2.14", optional = true }
clap = "2.33.3"

[dev-dependencies]
tokio-test = "0.3.0"

