[package]
name = "kvs"
version = "0.1.0"
authors = ["ymgyt <yamaguchi7073xtt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
cli = ["clap"]

[dependencies]
thiserror = "1.0.14"
serde = "1.0.106"

clap = {version = "2.33.0", optional = true}
byteorder = "1.3.4"


[[bin]]
name = "kvs"
path = "src/bin/kvs.rs"
required-features = ["cli"]
