[package]
name = "kvs"
version = "0.1.0"
authors = ["ymgyt <yamaguchi7073xtt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
cli = ["clap", "anyhow"]

[dependencies]
thiserror = "1.0.14"
serde = {version = "1.0.106", features = ["derive"]}
byteorder = "1.3.4"
crc32fast = "1.2.0"
bincode = "1.2.1"

clap = {version = "2.33.0", optional = true}
anyhow = {version = "1.0.28", optional = true}



[[bin]]
name = "kvs"
path = "src/bin/kvs.rs"
required-features = ["cli"]
